sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t tathya27/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tathya27/docker-react npm run test
